apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: quynt/gitops01:cc984cd31c71acb6981d7e5289211ed1bfd39a20
          imagePullPolicy: Always
          ports:
            - containerPort: 80
