# Deployment with HA considerations

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1  # Increase replicas for HA
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: quynt/gitops01:0b2e66170d11cb8b951e7ac10c484225a94dc67c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /  # Adjust path based on your health check endpoint
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "200m"