apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
spec:
    rules:
    - http:
        paths:
          - pathType: Prefix  # Handle requests starting with the specified path (optional)
            path: /  # Adjust the path prefix if your application needs a specific path
            backend:
              service:
                name: react-app  # Replace with the name of your service
                port:
                  number: 80