
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nifi-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nifi-app-pod
  template:
    metadata:
      labels:
        app: nifi-app-pod
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nifi-app
          image: quynt/nifi:1.23.1
          imagePullPolicy: IfNotPresent
          env:
            - name: NIFI_WEB_HTTPS_PORT
              value: 9080
          ports:
            - containerPort: 9080
